// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#ifdef CONFIGURATION_HEADER
  #include CONFIGURATION_HEADER
#endif

// Token header for the token.properties.
#include "protocol/zigbee_5.10/app/framework/util/tokens.h"

// Token header for the Bulb user interface plugin.
#include "protocol/zigbee_5.10/app/framework/plugin-soc/bulb-ui/bulb-ui-tokens.h"

// Token header for the Configuration server plugin.
#include "protocol/zigbee_5.10/app/framework/plugin-soc/configuration-server/configuration-server-tokens.h"

// Token header for the Manufacturing Library CLI plugin.
#include "protocol/zigbee_5.10/app/framework/plugin-soc/manufacturing-library-cli/manufacturing-library-cli-tokens.h"

// Token header for the Reporting plugin.
#include "protocol/zigbee_5.10/app/framework/plugin/reporting/reporting-tokens.h"

// Token header for the Scenes Server Cluster plugin.
#include "protocol/zigbee_5.10/app/framework/plugin/scenes/scenes-tokens.h"

#ifdef CUSTOM_TOKEN_HEADER
  #include CUSTOM_TOKEN_HEADER
#endif

