// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __AFV2_BOOKKEEPING_H__
#define __AFV2_BOOKKEEPING_H__


#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "af.h"

void emAfInit(void);

void emAfTick(void);

void emAfResetAttributes(uint8_t endpointId);

bool emAfPreCommandReceived(EmberAfClusterCommand* cmd);

bool emAfPreZDOMessageReceived(EmberNodeId emberNodeId,EmberApsFrame* apsFrame,uint8_t* message,uint16_t length);

bool emAfRetrieveAttributeAndCraftResponse(uint8_t endpoint, EmberAfClusterId clusterId, EmberAfAttributeId attrId, uint8_t mask, uint16_t maunfacturerCode, uint16_t readLength);

void emAfZigbeeKeyEstablishment(EmberEUI64 partner, EmberKeyStatus status);

#endif // __AFV2_BOOKKEEPING_H__
